---
abstract: 'A truly Pure Perl interface to Git repositories'
author:
  - 'Arthur Axel "fREW" Schmidt <frioux+cpan@gmail.com>'
build_requires:
  Archive::Extract: '0'
  Test::More: '0.88'
  Test::utf8: '0.02'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Cogit
requires:
  Check::ISA: '0'
  Compress::Raw::Zlib: '0'
  Compress::Zlib: '0'
  Config::GitLike: '0'
  Data::Stream::Bulk: '0'
  DateTime: '0'
  File::Find::Rule: '0'
  IO::Digest: '0'
  Moo: '0'
  MooX::Types::MooseLike: '0'
  namespace::clean: '0'
resources:
  bugtracker: https://github.com/frioux/Cogit/issues
  homepage: https://github.com/frioux/Cogit
  repository: https://github.com/frioux/Cogit.git
version: '0.001000'
